
services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PYTHON_VERSION_MAJOR: 3
        PYTHON_VERSION_MINOR: 13
        PYTHON_VERSION_PATCH: 1
    platform: linux/amd64
    ports:
      - "5001:5000"
    volumes:
      - /etc/localtime:/etc/localtime # sync container timezone with host
      - .:/opt/ffmwr # mount host repository directory
